In [1]:
import pandas as pd
file_path = "C:\Devdan College\DCU work\Statisticsal Data Analytics\open_food_facts_2025 (1).csv"
df = pd.read_csv(file_path)

df.head()

c:\python37\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,code,url,product_name,generic_name,quantity,countries,countries_en,origins,manufacturing_places,categories,...,sodium_100g,completeness,unique_scans_n,serving_size,creator,image_url,main_category_en,nova_group_label,created_date,last_modified_date
0,7,http://world-en.openfoodfacts.org/product/0000...,granola Bio le Chocolaté,NaN,450g,"Spanien, Germany","Germany,Spain",NaN,NaN,"Aliments et boissons à base de végétaux, Alime...",...,NaN,0.7625,2.0,25 gram,smoothie-app,https://images.openfoodfacts.org/images/produc...,Dried fruits,NaN,2023-03-14,2025-05-26
1,9,http://world-en.openfoodfacts.org/product/0000...,xytitol pastilles,NaN,700ml,"Germany,Spain","Germany,Spain",NaN,NaN,"it:Gestione sovrappeso, it:obesità, Wrap",...,NaN,0.5750,1.0,0g,openfoodfacts-contributors,https://images.openfoodfacts.org/images/produc...,it:obesita,NaN,2018-05-25,2025-06-11
2,13,http://world-en.openfoodfacts.org/product/0000...,Powdered peanut butter,NaN,300 g,en:Switzerland,Switzerland,NaN,NaN,"Snacks, Meals, Rice dishes, Risottos, Powder p...",...,NaN,0.9750,2.0,0g,jeff-krab,https://images.openfoodfacts.org/images/produc...,Powder-peanut-butter,NaN,2019-03-30,2025-04-10
3,15,http://world-en.openfoodfacts.org/product/0000...,Madeleines ChocoLait,NaN,1000 g,France,France,NaN,NaN,"Snacks, Snacks sucrés, Biscuits et gâteaux, Gâ...",...,NaN,0.7875,1.0,"21,6g",openfoodfacts-contributors,https://images.openfoodfacts.org/images/produc...,Chocolate madeleines,Ultra-processed foods,2018-04-15,2025-05-06
4,22,http://world-en.openfoodfacts.org/product/0000...,Farandole de madeleine,NaN,590 g,Brasil,Brazil,NaN,NaN,"Snacks, Snacks sucrés, Biscuits et gâteaux, Gâ...",...,NaN,0.8000,1.0,54g,openfoodfacts-contributors,https://images.openfoodfacts.org/images/produc...,Long madeleines,Ultra-processed foods,2021-02-28,2025-05-06

In [2]:
print("Duplicates found:", df.duplicated().sum()) #Finding Dupilcates in the selected dataset

Duplicates found: 0

In [3]:
# Selecting the assigned columns for data cleaning
target_cols = [
    'image_url', 'creator', 'created_date', 'last_modified_date', 'completeness', 
    'nutriscore_grade', 'ingredients_text', 'allergens', 'additives_n', 'additives_en'
]

# Drops the row if ANY of the 10 target columns contain a null value
df = df.dropna(subset=target_cols)

# Verify how many nulls remain in your 10 columns
print(df[target_cols].isnull().sum())

df = df.drop_duplicates()

image_url             0
creator               0
created_date          0
last_modified_date    0
completeness          0
nutriscore_grade      0
ingredients_text      0
allergens             0
additives_n           0
additives_en          0
dtype: int64

In [4]:
df['created_date'] = pd.to_datetime(df['created_date'], errors='coerce') #Changing the date format to default format pandas accept
df['last_modified_date'] = pd.to_datetime(df['last_modified_date'], errors='coerce')#Changing the date format to default format pandas accept

In [5]:
# Check the data types of your 10 columns
print(df[target_cols].dtypes)

# Preview just the 10 cleaned columns
df[target_cols].head()

image_url                     object
creator                       object
created_date          datetime64[ns]
last_modified_date    datetime64[ns]
completeness                 float64
nutriscore_grade              object
ingredients_text              object
allergens                     object
additives_n                  float64
additives_en                  object
dtype: object

,image_url,creator,created_date,last_modified_date,completeness,nutriscore_grade,ingredients_text,allergens,additives_n,additives_en
9,https://images.openfoodfacts.org/images/produc...,beniben,2016-12-01,2025-05-03,0.8875,D,"mûre bio 50% (fruit 27%, purée 23%) sucre de c...","en:eggs,en:gluten,en:milk,en:nuts",1.0,E440 - Pectins
41,https://images.openfoodfacts.org/images/produc...,beniben,2016-12-01,2024-10-04,0.8875,E,"Farine de _blé_, fourrage lait et caramel 17% ...","en:eggs,en:gluten,en:milk,en:soybeans",8.0,"E202 - Potassium sorbate,E322 - Lecithins,E422..."
51,https://images.openfoodfacts.org/images/produc...,kiliweb,2022-03-06,2025-04-29,0.7000,C,"Water, Mushroom (20%), Fortified Wheat Flour (...",en:sulphur-dioxide-and-sulphites,7.0,"E160a - Carotene,E160ai - Beta-carotene,E160c ..."
63,https://images.openfoodfacts.org/images/produc...,openfoodfacts-contributors,2019-05-28,2024-10-04,0.7875,E,"Sucre, œufs frais (34%), farine de blé, sirop ...","en:eggs,en:gluten",3.0,"E336 - Potassium tartrates,E415 - Xanthan gum,..."
65,https://images.openfoodfacts.org/images/produc...,kiliweb,2022-04-22,2024-12-11,0.7875,E,Amandes enrobées de chocolat au lait et poudre...,"en:gluten,en:milk,en:nuts",3.0,"E322 - Lecithins,E322i - Lecithin,E500 - Sodiu..."

In [6]:
# Remove the "en:" prefix from all rows in the allergens column
df['allergens'] = df['allergens'].str.replace('en:', '')

#Replace the commas with a comma and a space for better readability
df['allergens'] = df['allergens'].str.replace(',', ', ')

# Check the data types of your 10 columns
print(df[target_cols].dtypes)

# Preview just the 10 cleaned columns
df[target_cols].head()

image_url                     object
creator                       object
created_date          datetime64[ns]
last_modified_date    datetime64[ns]
completeness                 float64
nutriscore_grade              object
ingredients_text              object
allergens                     object
additives_n                  float64
additives_en                  object
dtype: object

,image_url,creator,created_date,last_modified_date,completeness,nutriscore_grade,ingredients_text,allergens,additives_n,additives_en
9,https://images.openfoodfacts.org/images/produc...,beniben,2016-12-01,2025-05-03,0.8875,D,"mûre bio 50% (fruit 27%, purée 23%) sucre de c...","eggs, gluten, milk, nuts",1.0,E440 - Pectins
41,https://images.openfoodfacts.org/images/produc...,beniben,2016-12-01,2024-10-04,0.8875,E,"Farine de _blé_, fourrage lait et caramel 17% ...","eggs, gluten, milk, soybeans",8.0,"E202 - Potassium sorbate,E322 - Lecithins,E422..."
51,https://images.openfoodfacts.org/images/produc...,kiliweb,2022-03-06,2025-04-29,0.7000,C,"Water, Mushroom (20%), Fortified Wheat Flour (...",sulphur-dioxide-and-sulphites,7.0,"E160a - Carotene,E160ai - Beta-carotene,E160c ..."
63,https://images.openfoodfacts.org/images/produc...,openfoodfacts-contributors,2019-05-28,2024-10-04,0.7875,E,"Sucre, œufs frais (34%), farine de blé, sirop ...","eggs, gluten",3.0,"E336 - Potassium tartrates,E415 - Xanthan gum,..."
65,https://images.openfoodfacts.org/images/produc...,kiliweb,2022-04-22,2024-12-11,0.7875,E,Amandes enrobées de chocolat au lait et poudre...,"gluten, milk, nuts",3.0,"E322 - Lecithins,E322i - Lecithin,E500 - Sodiu..."

In [7]:
# Save only the target columns as a CSV
df[target_cols].to_csv('cleaned_10_columns.csv', index=False)

In [8]:
# 1. Fix Allergen Spacing
# Using regex=True ensures that any weird multiple spaces after a comma become exactly one space
df['allergens'] = df['allergens'].str.replace(r',\s+', ', ', regex=True)

# 2. Convert Date Columns to Proper Datetime Format
df['created_date'] = pd.to_datetime(df['created_date'])
df['last_modified_date'] = pd.to_datetime(df['last_modified_date'])

# 3. Convert Additives Count from Decimal (float) to Integer (int)
df['additives_n'] = df['additives_n'].astype(int)

# 4. Save the fully polished dataset!
df.to_csv('fully_cleaned_10_columns.csv', index=False)

In [11]:
# 1. Remove unwanted symbols
# In Open Food Facts datasets, allergens in the ingredients text are often 
# surrounded by underscores (e.g., "_Lait_"). This removes them.
#df['ingredients_text'] = df['ingredients_text'].str.replace('_', '', regex=False)

# You can add additional characters to remove if you spot them, like asterisks:
df['ingredients_text'] = df['ingredients_text'].str.replace('*', '', regex=False)

# 2. Format to Sentence Case (Uppercase first letter, lowercase the rest)
df['ingredients_text'] = df['ingredients_text'].str.capitalize()

# 3. Define the 10 columns you want to keep
columns_to_keep = [
    'image_url', 'creator', 'created_date', 'last_modified_date', 
    'completeness', 'nutriscore_grade', 'ingredients_text', 
    'allergens', 'additives_n', 'additives_en'
]

# 4. Filter the dataset to include only those columns, then save it
df[columns_to_keep].to_csv('final_10_columns_only.csv', index=False)

In [14]:
import pandas as pd

# 1. Load your dataset
df = pd.read_csv('fully_cleaned_10_columns.csv')

# 2. Define the exact 10 columns you want to keep
columns_to_keep = [
    'image_url', 'creator', 'created_date', 'last_modified_date', 
    'completeness', 'nutriscore_grade', 'ingredients_text', 
    'allergens', 'additives_n', 'additives_en'
]

# 3. Filter for just those columns AND save with the correct Excel encoding
df[columns_to_keep].to_csv('final_10_columns_only.csv', index=False, encoding='utf-8-sig')